# try/except
print(1234)
print(5678)
try : int('abc')
except : print('ocorreu um erro')